services:
  db:
    image: amazon/dynamodb-local:3.3.1
    container_name: itala_db
    ports:
      - 8000:8000
    volumes:
      - ./.data/db:/home/dynamodblocal/data

  dba:
    image: aaronshaf/dynamodb-admin:5.3.4
    container_name: itala_dba
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://db:8000
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - db
