name: CD

on:
  push:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-southeast-1

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setup.outputs.environment }}
    steps:
      - id: setup
        run: |
          if [[ "$GITHUB_REF_NAME" == "develop" ]]; then
            echo "environment=staging" >> "$GITHUB_OUTPUT"
          elif [[ "$GITHUB_REF_NAME" == "master" ]]; then
            echo "environment=production" >> "$GITHUB_OUTPUT"
          else
            echo "Unsupported branch: $GITHUB_REF_NAME"
            exit 1
          fi

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.setup.outputs.environment }}
    steps:
      - name: Checkout
        uses: hyoaru/actions/checkout@v1

      - name: Setup Go
        uses: hyoaru/actions/setup-go@v1
        with:
          go-version-file: "go.mod"

      - name: Build lambda
        run: |
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o bootstrap cmd/lambda/main.go
          zip -j function.zip bootstrap

      - name: Upload build artifact
        uses: hyoaru/actions/upload-artifact@v1
        with:
          name: build-artifact
          path: function.zip
          if-no-files-found: error

  deploy:
    needs: [setup, build]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.setup.outputs.environment }}
    steps:
      - name: Download build artifact
        uses: hyoaru/actions/download-artifact@v1
        with:
          name: build-artifact
          path: .

      - name: Configure AWS credentials
        uses: hyoaru/actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get configuration
        run: |
          API_FUNCTION_S3_URI=$(aws ssm get-parameter \
            --name "/itala/api-function-s3-uri" \
            --query "Parameter.Value" \
            --output text)

          echo "API_FUNCTION_S3_URI=$API_FUNCTION_S3_URI" >> "$GITHUB_ENV"

      - name: Deploy to S3
        run: aws s3 cp function.zip "${{ env.API_FUNCTION_S3_URI }}"
